### ISSUE TITLE
AirTable 11.0.8 brakes Typo3 v11.5.14

### ISSUE THREAD

**Issue by anatol06** [iv-litovchenko/EXT-AirTable-CMS-TYPO3#1]
Hi!
I just wanted to inform you that after installation of AirTable 11.0.8 on Typo3 v11.5.14 it is not possilbe to login in backend any more. Also, it does not create any new positions in backend menu as shown on screenshot.
Is it possible to make it working on Typo3 v11 LTS?
Best wises
Anatol

**Comment by iv-litovchenko** [comment]
Hi Anatol!

It is will very big job when adaptation this extensions for typo3 11. Right now i dont can it. In ideal i will want make this with typo3  community.

**Comment by anatol06** [comment]
Ок. Спасибо за ответ. Я просто ищу инструменты для быстрой работы с этой системой и ваше расширение показалось интересным.

**Comment by iv-litovchenko** [comment]
Когда я разрабатывал на TYPO3 я получал очень большое удовольствие от этот разработки. Очень не хватает подобного простого функционала в системе из коробки.

**Comment by anatol06** [comment]
Для этой системы не хватает всего, в т .ч. и нормальных учебных видеокурсов. Не понимаю, почему в Германии она так популярна, когда есть Wordpress, Joomla в которыз все намного понятнее и проще.

**Comment by iv-litovchenko** [comment]
Не знаю ни одной системы на которой бы вы могли собрать очень большой проект энциклопедической направленности и который в первую очередь могли бы наполнять и редактировать обычные редакторы, а разработчики писать под него плагины в формате модульных расширений. Поэтому она и популярна, но со своими недостатками. Изначально насколько понимаю эта система была сделана для каких-то внутренних решений - т.к. имеет очень большой пласт вариаций настройки в плане доступов...

**Comment by iv-litovchenko** [comment]
Nice
